### ISSUE TITLE
Wiki page

### ISSUE THREAD

**Issue by ricardotaborda** [chemMD/Chem_Strip#34]
The Wiki page is rather slim with little documentation. Think of this, if I were a user and needed to know the basics about what the code does, how to download it, compile it, and make it run with an example... would I find the information I need in this wiki?

**Comment by cegallo2** [comment]
It definitely needs some work. It needs more information for the user.

**Comment by cegallo2** [comment]
Wiki page now has user instructions, longer descriptions and some images.
